version: '1.0'
name: npm-publish-20221206
displayName: npm-publish
triggers:
  trigger: auto
  push:
    tags:
      include:
        - /\d+.\d+.\d+/
stages:
  - name: stage-39568205
    displayName: 依赖安装并打包
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm config set registry https://registry.npmmirror.com
          - npm install pnpm -g
          - pnpm install
          - pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '1'
  - name: stage-1cb8dbc4
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - pnpm add @jsdevtools/npm-publish -g
          - npm-publish --token=$NPM_PUBLISH_TOKEN ./package.json
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '1'
