version: '1.0'
name: pipeline-20221219
displayName: pipeline-20221219
triggers:
  trigger: auto
  push:
    tags:
      include:
        - \d+\.\d+\.\d+
stages:
  - name: stage-7e7a5ab2
    displayName: 打包发布流程
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 安装pnpm'
          - npm install pnpm -g
          - '# 执行编译命令'
          - npm config set registry https://registry.npmjs.org
          - git config --global user.email "gitee@pipeline.com"
          - git config --global user.name "GiteePipeline"
          - pnpm install && pnpm run build && node release
          - '# 更新组件库文档'
          - pnpm run docs:build && cd docs/.vitepress/dist
          - git init && git add . && git commit -m 'docs update'
          - git remote add origin https://oauth2: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@gh.zhuiyue.work/github.com/zhuiyue132/component-docs.git
          - git branch -M main
          - git push -u -f origin main
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
