version: '1.0'
name: pipeline-20221219
displayName: pipeline-20221219
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v([1-9]\d|[1-9])(\.([1-9]\d|\d)){2}
stages:
  - name: stage-7e7a5ab2
    displayName: 打包发布流程
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - npm install pnpm -g
          - '# 执行编译命令'
          - pnpm install && pnpm run build && node release
          - 
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
